name: Hello World

on:
  push:  # Trigger the workflow on push events
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest  # Use the ubuntu-latest runner

    steps:
      - name: Echo text  # Step name
        run: echo "Hello, world!"  # Command to run
      # Add a step to list directory and files

      - name: List files and folders
        run: ls -la
      
      

